# Generated by Django 5.2 on 2025-04-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome da turma')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome do professor')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('time', models.CharField(max_length=20, verbose_name='horário')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.classgroup', verbose_name='turma')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.teacher', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome do aluno')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.classgroup', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('pk', models.CompositePrimaryKey('student', 'date_attendance', 'lesson', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_attendance', models.DateField(auto_now_add=True)),
                ('present', models.BooleanField(default=False, verbose_name='presente')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.lesson', verbose_name='aula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'presença',
                'verbose_name_plural': 'presenças',
            },
        ),
    ]
