# Generated by Django 5.2 on 2025-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='cor'),
        ),
    ]
