# Generated by Django 5.2 on 2025-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='telefone'),
        ),
    ]
